### ISSUE TITLE
SFML version

### ISSUE THREAD

**Issue by budaimdev** [jetbrains-academy/CppBasics#84]
Hi, I don't know, if anyone already mentioned this issue, but the SFML version used in CMakeLists.txt is too old. Whenever I want to do the Moving On part, I have to manually edit this part

```
    find_package(SFML 2.5.1 COMPONENTS system window graphics network audio)
```
to this
```
    find_package(SFML 3.0.1 COMPONENTS System Window Graphics Network Audio)
```

and rewrite main.cpp and other files to match the newer version. I'm on Arch Linux, and I can't download older version of SFML.

All errors that I got [errors.txt](https://github.com/user-attachments/files/21739941/errors.txt)

**Comment by ramirocantu** [comment]
Issue is fixed by editing cmake/sfml-download.cmake, sorry I had my own issues with building where my version of cmake was too recent to where one of the build minimums defined by SFML was no longer supported by cmake and build would fail. I should have read your issue more clearly, but looks like the best fix is to update sfml-download.cmake to 3.0.1 to fix both issues.

**Comment by kochaika** [comment]
@KovalevRoma can you please verify that this issue no longer reproduces in the new version of the course.

**Comment by unleashrain** [comment]
Hi @kochaika I created a new issue for this before I saw this comment. I am still experiencing this issue on my end. M4 Mac

**Comment by kochaika** [comment]
Hi @LahevOdVika !
Since the course currently uses sfml v2, have you tried to build this version from sources?
